import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./(components)/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'Next Tutorial',
    template: '%s | PL'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-my-dark flex w-screen h-screen p-5`}
      >
        <div className="h-full min-w-64 px-4 mr-5">
          <Sidebar />
        </div>

        <main className="h-full w-full">
          <div className="bg-slate-100 h-full p-6 rounded-3xl">
            {children}
          </div>
        </main>

      </body>
    </html>
  );
}
